SELECT P.ProductName AS Nombre_Producto
FROM Products P
JOIN OrderDetails OD ON P.ProductID = OD.ProductID
JOIN Orders O ON OD.OrderID = O.OrderID
JOIN Employees E ON O.EmployeeID = E.EmployeeID
GROUP BY P.ProductID, P.ProductName
HAVING COUNT(DISTINCT E.EmployeeID) = (SELECT COUNT(*) FROM Employees)
ORDER BY P.ProductName;

SELECT DISTINCT C.CONTACTNAME AS CLIENTE
FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMERID = O.CUSTOMERID
JOIN ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
JOIN PRODUCTS P ON OD.PRODUCTID = P.PRODUCTID
WHERE P.UNITPRICE < 50
ORDER BY C.CONTACTNAME ASC;

SELECT DISTINCT E.TITLE AS TITULO, E.FIRSTNAME AS NOMBRE
FROM EMPLOYEES E
JOIN ORDERS O ON E.EMPLOYEEID = O.EMPLOYEEID
JOIN ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
JOIN PRODUCTS P ON OD.PRODUCTID = P.PRODUCTID
WHERE P.PRODUCTNAME IN ('GRAVAD LAX','MISHI KOBE NIKU')
ORDER BY E.FIRSTNAME ASC;

SELECT DISTINCT E.FIRSTNAME AS NOMBRE_EMPLEADO, C.CONTACTNAME AS NOMBRE_CLIENTE
FROM EMPLOYEES E
JOIN ORDERS O ON E.EMPLOYEEID = O.EMPLOYEEID
JOIN CUSTOMERS C ON O.CUSTOMERID = C.CUSTOMERID
JOIN SHIPPERS S ON S.SHIPPERID = O.SHIPVIA
WHERE S.COMPANYNAME = "SPEEDY EXPRESS" AND C.CITY = "BRUXELLES";

SELECT DISTINCT E.FIRSTNAME AS NOMBRE, E.ADDRESS AS DIRECCION, E.CITY AS CIUDAD, E.REGION AS REGION
FROM EMPLOYEES E
JOIN ORDERS O ON E.EMPLOYEEID = O.EMPLOYEEID
JOIN CUSTOMERS C ON O.CUSTOMERID = C.CUSTOMERID
WHERE O.SHIPCOUNTRY = "BELGIUM"
ORDER BY E.FIRSTNAME ASC;